/**
 * Branscombe Estate — 37-unit residential development
 * Source: Unison architectural drawing 20E92-03 (RevC, 2021),
 *         block "20E92-03 - proposed site plan"
 *         Planning permit PLN-21-408.02 (Glenorchy City Council).
 *
 * Site: 122-124 Branscombe Road, Claremont TAS 7011
 * 37 single-storey homes by Unison (36 x 3-bed/2-bath + Unit 31 x 2-bed per approved DA),
 * 7 Star Energy rated.
 *
 * Polygons (per-home footprints, site boundary, roads, kerbs, decks, POS) live
 * in ./polygons.json — generated by scripts/branscombe-extract/04_extract_polygons.py
 * from the Unison DWG. Coordinates in SVG-space, Y-down, viewBox 0 0 1000 ~917.
 *
 * GeoJSON (./geojson.json) — pending. Requires cadastral two-point fit before
 * Mapbox satellite overlay can render correctly.
 */

export type HouseType = "1A" | "1B" | "2A" | "2B" | "2C";

/**
 * Where a home's dedicated car spaces sit relative to the dwelling.
 * Raw workbook values: "Under Home" / "Exterior Besides" / "Exterior Near" /
 * "Exterior Besides/Near".
 */
export type ParkingLocation =
  | "under_home"
  | "exterior_beside"
  | "exterior_near"
  | "exterior_beside_near";

export interface ParkingInfo {
  /** Dedicated resident car spaces for this home (per-lot, not hardcoded). */
  spaces: number;
  /** Where those spaces sit relative to the home. */
  location: ParkingLocation;
  /** Human-readable label for display (see PARKING_LOCATION_LABEL). */
  locationLabel: string;
}

/** Canonical display strings for each parking location. */
export const PARKING_LOCATION_LABEL: Record<ParkingLocation, string> = {
  under_home: "Under home",
  exterior_beside: "Beside home",
  exterior_near: "Near home",
  exterior_beside_near: "Beside / near home",
};

export interface UnitData {
  /** Unit identifier — "U1" through "U37". */
  id: string;
  /** Numeric unit (1..37). */
  unitNumber: number;
  /** Unison house type group. */
  type: HouseType;
  /** Geographic zone within the site (informational). */
  zone: string;
  /** Resident car parking for this home. */
  parking: ParkingInfo;
}

function unit(
  n: number,
  type: HouseType,
  zone: string,
  parkingLocation: ParkingLocation,
  parkingSpaces = 2,
): UnitData {
  return {
    id: `U${n}`,
    unitNumber: n,
    type,
    zone,
    parking: {
      spaces: parkingSpaces,
      location: parkingLocation,
      locationLabel: PARKING_LOCATION_LABEL[parkingLocation],
    },
  };
}

/**
 * All 37 units, ordered by unit number.
 * Type assignment per Unison architectural set (matches floor plans
 * Type 1A/1B = 104m² home, Type 2A/2B/2C = 114m² home, all + 24m² deck).
 */
export const UNITS: UnitData[] = [
  unit(1,  "1A", "SW Entry",   "exterior_beside"),
  unit(2,  "1B", "SW Entry",   "exterior_beside"),
  unit(3,  "1A", "SW Mid",     "exterior_beside"),
  unit(4,  "2A", "SW Mid",     "exterior_beside"),
  unit(5,  "2B", "SW Entry",   "exterior_near"),
  unit(6,  "2C", "SW Entry",   "exterior_near"),
  unit(7,  "1B", "Mid West",   "exterior_beside"),
  unit(8,  "2A", "Mid West",   "exterior_beside"),
  unit(9,  "1A", "Mid West",   "exterior_beside"),
  unit(10, "2B", "North Mid",  "exterior_beside"),
  unit(11, "1A", "North West", "exterior_beside"),
  unit(12, "1B", "North West", "under_home"),
  unit(13, "2A", "North",      "under_home"),
  unit(14, "1A", "North",      "exterior_beside"),
  unit(15, "2B", "North",      "under_home"),
  unit(16, "2C", "North",      "exterior_beside"),
  unit(17, "1B", "North Mid",  "under_home"),
  unit(18, "2A", "NE",         "exterior_beside"),
  unit(19, "1A", "NE Mid",     "under_home"),
  unit(20, "2B", "NE",         "exterior_beside"),
  unit(21, "2C", "East Mid",   "under_home"),
  unit(22, "1A", "East",       "exterior_beside"),
  unit(23, "1B", "East Mid",   "under_home"),
  unit(24, "2A", "SE Mid",     "exterior_beside"),
  unit(25, "2B", "SE Mid",     "under_home"),
  unit(26, "2C", "SE",         "exterior_beside"),
  unit(27, "1A", "SE",         "under_home"),
  unit(28, "1B", "SE",         "exterior_beside"),
  unit(29, "2A", "South",      "under_home"),
  unit(30, "2B", "South",      "under_home"),
  unit(31, "2C", "SE Corner",  "exterior_beside"),
  unit(32, "1A", "SE Corner",  "exterior_near"),
  unit(33, "1B", "East Lower", "under_home"),
  unit(34, "2A", "East Lower", "exterior_beside"),
  unit(35, "2B", "East Lower", "exterior_beside"),
  unit(36, "2C", "East Mid",   "exterior_beside"),
  unit(37, "1A", "East",       "exterior_near"),
];

export const HOUSE_TYPE_INFO: Record<HouseType, {
  label: string;
  size: string;
  /** Numeric home area in m² (sans deck). */
  homeAreaM2: number;
  /** Numeric deck area in m². */
  deckAreaM2: number;
  /** Pre-formatted deck string for display ("24m² deck"). */
  deck: string;
  beds: number;
  baths: number;
  /** Display colour for the home footprint on the plan view. */
  color: string;
  /** Outline colour for the home footprint. */
  border: string;
}> = {
  "1A": { label: "Type 1A", size: "104m²", homeAreaM2: 104, deckAreaM2: 24, deck: "24m² deck", beds: 3, baths: 2, color: "#00B5AD", border: "#007F78" },
  "1B": { label: "Type 1B", size: "104m²", homeAreaM2: 104, deckAreaM2: 24, deck: "24m² deck", beds: 3, baths: 2, color: "#0097A7", border: "#005F66" },
  "2A": { label: "Type 2A", size: "114m²", homeAreaM2: 114, deckAreaM2: 24, deck: "24m² deck", beds: 3, baths: 2, color: "#7B1FA2", border: "#4A0F60" },
  "2B": { label: "Type 2B", size: "114m²", homeAreaM2: 114, deckAreaM2: 24, deck: "24m² deck", beds: 3, baths: 2, color: "#512DA8", border: "#311B66" },
  "2C": { label: "Type 2C", size: "114m²", homeAreaM2: 114, deckAreaM2: 24, deck: "24m² deck", beds: 3, baths: 2, color: "#303F9F", border: "#1B2563" },
};

/**
 * Notional land area per unit (m²), keyed by unit number.
 * Source: Branscombe_Unit_Schedule.xlsx → "Unit Schedule" sheet, "Notional land
 * (m²)" column (DA Branscombe Modular GFA Foundation Model, 23 Dec 2025).
 * Per-unit apportioned land — not a surveyed lot boundary (these are strata-style
 * dwellings on a single title). Imported 2026-06-05.
 */
export const NOTIONAL_LAND_M2: Record<number, number> = {
  1: 550, 2: 545, 3: 545, 4: 535, 5: 540, 6: 535, 7: 510, 8: 510, 9: 515,
  10: 510, 11: 520, 12: 490, 13: 485, 14: 455, 15: 480, 16: 450, 17: 480,
  18: 450, 19: 480, 20: 450, 21: 480, 22: 445, 23: 495, 24: 455, 25: 500,
  26: 460, 27: 495, 28: 460, 29: 505, 30: 510, 31: 375, 32: 350, 33: 405,
  34: 350, 35: 370, 36: 385, 37: 410,
};

/**
 * Estate-level parking totals (not per-home).
 * Source: "122-124 Branscombe Rd - Parking.xlsx" totals + the approved Traffic
 * Impact Assessment (84 required, 87 provided). Do not round or recompute.
 */
export const ESTATE_PARKING = {
  residentSpacesPerUnit: 2,
  totalResidentSpaces: 74,
  visitorSpaces: 13,
  totalSpaces: 87,
} as const;

/** Convenience lookup: unit id -> UnitData. */
export const UNIT_BY_ID: Record<string, UnitData> = Object.fromEntries(
  UNITS.map((u) => [u.id, u]),
);

/** All home types in display order. */
export const HOUSE_TYPES: HouseType[] = ["1A", "1B", "2A", "2B", "2C"];
